# Maps the values of repository_ctx.os.name and repository_ctx.os.arch to the
# os and cpu names used in multitool.lock.json.
_OS_NAMES = {
    "linux": "linux",
    "mac os x": "macos",
}

_CPU_NAMES = {
    "aarch64": "arm64",
    "amd64": "x86_64",
    "arm64": "arm64",
    "x86_64": "x86_64",
}

# The rain binary for each supported "{os}_{cpu}" pair. The repos are imported
# under these names by use_repo in MODULE.bazel.
#
# rain publishes one macOS binary, built for x86_64. On arm64 macOS it runs
# under Rosetta 2.
_TOOL_REPOS = {
    "linux_x86_64": Label("@rain_linux_x86_64//tools/rain:linux_x86_64_executable"),
    "macos_arm64": Label("@rain_macos_arm64//tools/rain:macos_arm64_executable"),
    "macos_x86_64": Label("@rain_macos_x86_64//tools/rain:macos_x86_64_executable"),
}


_COMMON_ATTRS = {
        "timeout": attr.int(
            doc = "The timeout in seconds for the download.",
            default = 200000,
        ),
        "integrity": attr.string(
            doc = "The integrity signature of this file",
            mandatory = True,
        ),
        "quiet": attr.bool(
            default = True,
            doc = "Whether to omit printing download progress",
        ),
        "file": attr.string(
            doc = "The name of the file to use for the downloaded file.",
        ),
}


def _get_tool_label(ctx):
    """Obtains the label of the multitool binary target to use for downloading
    the files.

    This performs a function similar to toolchain resolution in ordinary rules.
    Except repo rules don't have this API, so we have to make do.

    Fails with a readable message on a host that has no rain binary.
    """
    platform = "{}_{}".format(
        _OS_NAMES.get(ctx.os.name, ctx.os.name),
        _CPU_NAMES.get(ctx.os.arch, ctx.os.arch),
    )
    if platform not in _TOOL_REPOS:
        fail("rules_bittorrent: no rain binary for host {} (os.name={}, os.arch={}). Supported: {}".format(
            platform,
            ctx.os.name,
            ctx.os.arch,
            ", ".join(sorted(_TOOL_REPOS.keys())),
        ))
    return _TOOL_REPOS[platform]


def _bt_common(ctx):
    quiet = ctx.attr.quiet
    uri = ctx.attr.uri
    if uri.startswith("@@//:"):
        uri = "/".join([str(ctx.workspace_root), uri[5:]])
    tool_path = str(ctx.path(_get_tool_label(ctx)))
    filename = ctx.attr.file or ctx.attr.name
    # rain listens on port 7246 for both RPC and DHT by default. Bazel fetches
    # repositories in parallel, so two rain processes started with the
    # defaults collide on that port. The download command does not need RPC,
    # and port 0 lets the OS pick a free DHT port.
    ctx.file("config.yaml", """#
resume-on-startup: true
dht-enabled: true
dht-port: 0
rpc-enabled: false
""")
    # The resume file resume_file_path
    resume_file_path = "/tmp/_bazel.{}.resume".format(ctx.attr.name)
    args = [
        tool_path, "download",
        "--config", "config.yaml",
        "--torrent", uri,
        "--resume", resume_file_path
    ]
    result = ctx.execute(args, quiet = quiet, timeout = ctx.attr.timeout)
    if result.return_code != 0:
        fail("rules_bittorrent: rain failed to download {} (exit code {}):\n{}\n{}".format(
            uri,
            result.return_code,
            result.stdout,
            result.stderr,
        ))
    # If the download was a success, remove the resume file, to ensure that
    # subsequent downloads complete.
    # See: https://github.com/cenkalti/rain/issues/205
    ctx.delete(resume_file_path)
    return filename


def _bt_file_impl(ctx):
    filename = _bt_common(ctx)
    ctx.file(
        "BUILD.bazel",
        """# Autogenerated, do not edit.

# @<repo_name>//:file
filegroup(
    name = "file",
    srcs = [
        "{name}",
    ],
)
exports_files([
    "{name}",
])
""".format(name=filename),
    )



bt_file = repository_rule(
    implementation = _bt_file_impl,
    attrs = _COMMON_ATTRS | {
        "uri": attr.string(
            doc = "The torrent URI to download the file from.",
            mandatory = True,
        ),
    },
)


def _bt_archive_impl(ctx):
    filename = _bt_common(ctx)
    if ctx.attr.extract:
        ctx.extract(filename, strip_prefix=ctx.attr.strip_prefix)
    ctx.file("BUILD.bazel", ctx.attr.build_file_content.format(name=filename))


bt_archive = repository_rule(
    implementation = _bt_archive_impl,
    attrs = _COMMON_ATTRS | {
        "uri": attr.string(
            doc = "The torrent URI to download the file from.",
            mandatory = True,
        ),
        "build_file_content": attr.string(
            doc = "The content of the build file to place in the repo",
            mandatory = True,
        ),
        "strip_prefix": attr.string(
            doc = "The prefix (directory) within the archive to strip away",
            default = '',
        ),
        "extract": attr.bool(
            default = True,
            doc = "Whether to extract the downloaded torrent (torrent with multiple files may not need this)",
        ),
    },
)
