name: Bazel CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docs
        run: bazel build //:repo.doc_extract

      - name: Check the current dir
        run: bash -c "ls -l bazel-bin/*"

      - name: Check bazel-bin
        run: bash -c "ls -l bazel-bin"

      - name: Create bazel-bin text archive
        run: |
          find bazel-bin/ -name "*.doc_extract.binaryproto" -print0 \
          | tar -czvf bazel-bin-output.tgz --null -T - --transform 's/^bazel-bin\///g' \
          && ls -l *.tgz \
          && tar tfv bazel-bin-output.tgz

      - name: "Integration test"
        working-directory: ./integration
        run: bazel build @test_repo//:file

