name: Bazel CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/MODULE.bazel', '**/WORKSPACE') }}-${{ hashFiles('**/bazel.rc') }}
          restore-keys: |
            bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/MODULE.bazel', '**/WORKSPACE') }}-
            bazel-cache-

      - name: Build @ubuntu//:file
        working-directory: ./integration
        run: bazel build @test_repo//:file
