# Based on the instructions at https://github.com/bazel-contrib/publish-to-bcr
name: Publish to my Bazel registry

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to publish"
        required: true
        type: string

jobs:
  publish:
    uses: "bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.2.3"
    with:
      tag_name: ${{ inputs.tag_name }}
      registry: filmil/bazel-registry
      registry_fork: filmil/bazel-registry
      attest: false
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}

